# Generated by Django 3.0.3 on 2020-02-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=225)),
                ('sender', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=225)),
            ],
        ),
    ]
