# Generated by Django 3.0.3 on 2020-02-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMonitoring', models.BooleanField(default=False)),
                ('isDrowsy', models.BooleanField(default=False)),
            ],
        ),
    ]
